# Generated by Django 5.1 on 2025-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
