# Generated by Django 5.1 on 2025-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name': 'parking', 'verbose_name_plural': 'parkings'},
        ),
        migrations.AlterModelOptions(
            name='slots',
            options={'verbose_name': 'slot', 'verbose_name_plural': 'slots'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='isAvailable',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='slotId',
            new_name='slot_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AlterModelTable(
            name='parking',
            table='parking',
        ),
        migrations.AlterModelTable(
            name='slots',
            table='slot',
        ),
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
    ]
