# Generated by Django 5.1 on 2025-03-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_parking_options_alter_slots_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
