# Generated by Django 5.1 on 2025-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_updatedat_parking_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='idNo',
            new_name='id_no',
        ),
    ]
